#SELECT * FROM OFFLINE_SALE
SELECT 
 PRODUCT.PRODUCT_CODE AS PRODUCT_CODE,
 (SUM(SALES_AMOUNT) * PRODUCT.PRICE) AS SALES
FROM OFFLINE_SALE
JOIN PRODUCT ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY OFFLINE_SALE.product_id
ORDER BY SALES DESC, PRODUCT_CODE ASC