SELECT 
 ID,
 GENOTYPE,
 (SELECT GENOTYPE FROM ECOLI_DATA WHERE ID = BASE.PARENT_ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA AS BASE
WHERE PARENT_ID IS NOT NULL AND
(BASE.GENOTYPE & (SELECT GENOTYPE FROM ECOLI_DATA WHERE ID = BASE.PARENT_ID)) = (SELECT GENOTYPE FROM ECOLI_DATA WHERE ID = BASE.PARENT_ID)
ORDER BY ID ASC