SELECT 
    YEAR(DIFFERENTIATION_DATE) YEAR,
    (MAX_DATA.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
    FROM (
        select *, YEAR(DIFFERENTIATION_DATE) YEAR
        from ECOLI_DATA
    ) BASE_DATA
    
    JOIN(
        SELECT 
            MAX(SIZE_OF_COLONY) AS MAX_SIZE,
            YEAR(DIFFERENTIATION_DATE) AS YEAR
        FROM ECOLI_DATA
        GROUP BY YEAR
    ) AS MAX_DATA 
    ON BASE_DATA.YEAR = MAX_DATA.YEAR
    ORDER BY 1, 2;
