-- 코드를 작성해주세요
SELECT INFO_BASE.ID, NAME_BASE.FISH_NAME, INFO_BASE.LENGTH FROM FISH_INFO AS INFO_BASE
JOIN FISH_NAME_INFO AS NAME_BASE ON INFO_BASE.FISH_TYPE = NAME_BASE.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) AS MAX_DATA ON INFO_BASE.FISH_TYPE = MAX_DATA.FISH_TYPE AND INFO_BASE.LENGTH = MAX_DATA.LENGTH
ORDER BY INFO_BASE.ID ASC