SELECT m.FOOD_TYPE, m.REST_ID, m.REST_NAME, m.FAVORITES
FROM REST_INFO as m
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES
    FROM REST_INFO GROUP BY FOOD_TYPE ORDER BY FOOD_TYPE DESC) AS s
ON m.FAVORITES = s.FAVORITES AND m.FOOD_TYPE = s.FOOD_TYPE
ORDER BY m.FOOD_TYPE DESC