SELECT
 SUM(GRADE.SCORE) AS SCORE,
 GRADE.EMP_NO,
 EMPLOYEES.EMP_NAME,
 EMPLOYEES.POSITION,
 EMPLOYEES.EMAIL
FROM HR_GRADE AS GRADE
JOIN HR_EMPLOYEES AS EMPLOYEES ON GRADE.EMP_NO = EMPLOYEES.EMP_NO
GROUP BY GRADE.EMP_NO
ORDER BY SUM(GRADE.SCORE) DESC
LIMIT 1