SELECT
 ICECREAM.INGREDIENT_TYPE,
 SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS HALF
JOIN ICECREAM_INFO AS ICECREAM ON HALF.FLAVOR=ICECREAM.FLAVOR
GROUP BY ICECREAM.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC
